### ISSUE TITLE
What BLAST-output format is required as input?

### ISSUE THREAD

**Issue by claczny** [AstrorEnales/BlastToSam#1]
Hi,

thanks for this nice tool!
I am looking forward to using it.
Could you please specify (maybe also in the README) what BLAST output format is supposed to be the input (ASN.1, XML, etc.)?

Thank you very much.

Best,

Cedric

**Comment by AstrorEnales** [comment]
It currently supports the output of blastn with "-outfmt 0" (pairwise). If you need any other output format supported, just let me know. I'll add this information to the README.
Thanks for your interest in this tool :)
Cheers,
Marcel

**Comment by claczny** [comment]
Thanks for your quick reply!

On a different note, can you potentially share any estimate of your tool's performance when considering an alignment of around 4 Mio. genes to a _de novo_  assembled genome fragmented into 43 contigs (all bacterial)?
The pairwise alignment file is about 1.1Gb in filesize.

**Comment by claczny** [comment]
Ooooops, got the following

```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: -1
        at java.util.ArrayList.elementData(ArrayList.java:400)
        at java.util.ArrayList.get(ArrayList.java:413)
        at MatchAlignment.getSequence(Unknown Source)
        at MatchAlignment.getCigar(Unknown Source)
        at BlastToSam.main(Unknown Source)
```

when doing the opposite: 43 contigs (query) vs. 4 Mio. genes (target)...

**Comment by AstrorEnales** [comment]
The error you encountered should be fixed now. You probably have some N in your sequence and that wasn't covered properly in building complementary sequences. Besides when any other unknown character is now detected it won't crash any more and just output an info message. Hope it now runs through.

Beside that, your use case is the first for this tool with such a big file and that much sequences. I hope it can handle it. In terms of performance the biggest blastn output i tested was around 340MB with 194 sequences queried on the "human genome golden path GRCh38", which it processed in under 3 minutes on my machine. But i'll make some measurements once i got a bit more time. The other thing is, that the tool runs everything "in-memory" because of the sorting orders. I hope your machine has enough memory to handle that for you 1.1Gb file. I planned changing this to work "on-disc", but there wasn't the need for that yet.

**Comment by claczny** [comment]
Thanks for the quick fix!

Memory is luckily not an issue as this runs on an HPC infrastructure. But it did not terminate after 30 minutes and I aborted the run.
Along this, I was wondering how the tool handles the "No hits found" cases in the pairwise output? Because I have literally millions of them and somehow guess that this might be a good place to speed things up considerably.
Maybe it would be (easily?) possible to add an option which is similar to the "-F 4" option in samtools to ignore unmapped reads? 

What do you think about that?

**Comment by AstrorEnales** [comment]
"No hits found" shouldn't be an issue in parsing and only take the time to write the query entry into the output file. However i added a command line parameter "-r" which excludes these queries from the output sam file.
Besides that, i improved the performance and memory usage and also added some console output to the program, so now it's not running "blind" any more and you can see in which state it currently is.

I tested it with a ~350MB blast output with 898 query sequences and 801889 alignments and it took 17 seconds on my 3.3GHz dual core.
The normal output for a full run should look like this:
[Info] BlastToSam v2015-05-12
[Info] Converting 'result.txt' to 'result.sam'
[Info] SortingOrder is coordinate
[Info] NameMode is cut
[Info] Reading input file...
[Info] Query count: 898
[Info] Reference count: 170
[Info] Alignments count: 801889
[Info] Sorting in coordinate mode...
[Info] Writing output...
[Info] Took 17.018sec

Hope it now works for you :) and at least we should now see at which point in the process it takes too long. I'll further try to improve the overall performance now.
